run:
    timeout: 10m
    tests: false
    allow-parallel-runners: true

linters-settings:
  staticcheck:
    go: "1.17"
  stylecheck:
    go: "1.17"
  cyclop:
    skip-tests: true
  misspell:
    locale: GB
  goimports:
    local-prefixes: github.com/yitsushi/go-aoc
  govet:
    check-shadowing: true
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: false
  varnamelen:
    ignore-names:
    - err
    - idx

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
  - text: "github.com/yitsushi/go-aoc/"
    linters:
    - wrapcheck
  - text: "https://"
    linters:
    - lll
  - path: _test\.go
    linters:
    - goerr113
    - gocyclo
    - errcheck
    - gosec
    - dupl
    - funlen
    - testpackage

linters:
  enable-all: true
  disable:
  - golint     # deprecated
  - interfacer # deprecated
  - ireturn
  - maligned   # deprecated
  - scopelint  # deprecated
